import type {
  AriaObservation,
  GwAgentEvent,
  RewardBreakdown,
} from "@/lib/contracts";

export const MOCK_SESSION_ID = "demo";

export const mockRewardBreakdown: RewardBreakdown = {
  task_completion: 0.72,
  relationship_health: 0.41,
  user_satisfaction: 0.58,
  time_efficiency: 0.34,
  conflict_resolution: 0.66,
  safety: 0.9,
  total: 0.58,
};

export const mockRunningTotal: RewardBreakdown = {
  task_completion: 4.6,
  relationship_health: 2.8,
  user_satisfaction: 3.9,
  time_efficiency: 2.1,
  conflict_resolution: 3.4,
  safety: 5.6,
  total: 3.5,
};

export const mockObservation: AriaObservation = {
  done: false,
  reward: 0.58,
  metadata: {},
  time: 9.5,
  location: "home",
  scenario_category: "calendar_conflict",
  difficulty: "medium",
  step_count: 7,
  max_steps: 50,
  preferences: Array.from({ length: 64 }, (_, i) =>
    Math.sin(i * 0.31) * 0.4,
  ),
  calendar: [
    {
      event_id: "ev_0001",
      day_offset: 0,
      start_hour: 10.0,
      end_hour: 11.0,
      title: "Design review with Priya",
      priority: 0.8,
      flexibility: 0.2,
      participant_ids: ["c_priya"],
      location: "office",
    },
    {
      event_id: "ev_0002",
      day_offset: 0,
      start_hour: 10.5,
      end_hour: 11.5,
      title: "Dentist appointment",
      priority: 0.6,
      flexibility: 0.7,
      participant_ids: [],
      location: "other",
    },
    {
      event_id: "ev_0003",
      day_offset: 0,
      start_hour: 13.0,
      end_hour: 14.0,
      title: "Lunch with Marco",
      priority: 0.4,
      flexibility: 0.8,
      participant_ids: ["c_marco"],
      location: "other",
    },
    {
      event_id: "ev_0004",
      day_offset: 1,
      start_hour: 9.0,
      end_hour: 10.0,
      title: "1:1 with manager",
      priority: 0.9,
      flexibility: 0.1,
      participant_ids: ["c_boss"],
      location: "office",
    },
    {
      event_id: "ev_0005",
      day_offset: 2,
      start_hour: 18.0,
      end_hour: 20.0,
      title: "Anniversary dinner",
      priority: 1.0,
      flexibility: 0.0,
      participant_ids: ["c_partner"],
      location: "other",
    },
    {
      event_id: "ev_0006",
      day_offset: 3,
      start_hour: 14.0,
      end_hour: 15.5,
      title: "Roadmap sync",
      priority: 0.7,
      flexibility: 0.3,
      participant_ids: ["c_boss", "c_priya"],
      location: "office",
    },
    {
      event_id: "ev_0007",
      day_offset: 5,
      start_hour: 11.0,
      end_hour: 12.0,
      title: "Doctor follow-up",
      priority: 0.85,
      flexibility: 0.2,
      participant_ids: [],
      location: "other",
    },
  ],
  inbox: [
    {
      email_id: "em_01",
      sender_id: "c_boss",
      subject: "Q3 planning — need your draft by EOD",
      urgency: 0.95,
      age_hours: 2.3,
      requires_reply: true,
      sentiment: -0.1,
    },
    {
      email_id: "em_02",
      sender_id: "c_partner",
      subject: "Reservation confirmed for Thursday",
      urgency: 0.3,
      age_hours: 6.0,
      requires_reply: false,
      sentiment: 0.6,
    },
    {
      email_id: "em_03",
      sender_id: "c_vendor",
      subject: "Invoice #4412 past due",
      urgency: 0.8,
      age_hours: 48.0,
      requires_reply: true,
      sentiment: -0.3,
    },
    {
      email_id: "em_04",
      sender_id: "c_priya",
      subject: "Design mock v2 — feedback?",
      urgency: 0.55,
      age_hours: 18.0,
      requires_reply: true,
      sentiment: 0.2,
    },
    {
      email_id: "em_05",
      sender_id: "c_marco",
      subject: "Still on for lunch?",
      urgency: 0.45,
      age_hours: 4.5,
      requires_reply: true,
      sentiment: 0.4,
    },
    {
      email_id: "em_06",
      sender_id: "c_hr",
      subject: "Benefits enrollment closes Friday",
      urgency: 0.5,
      age_hours: 30.0,
      requires_reply: false,
      sentiment: 0.0,
    },
    {
      email_id: "em_07",
      sender_id: "c_mom",
      subject: "Did you book the flight?",
      urgency: 0.7,
      age_hours: 12.0,
      requires_reply: true,
      sentiment: 0.3,
    },
    {
      email_id: "em_08",
      sender_id: "c_friend",
      subject: "Weekend hike?",
      urgency: 0.2,
      age_hours: 20.0,
      requires_reply: true,
      sentiment: 0.5,
    },
    {
      email_id: "em_09",
      sender_id: "c_newsletter",
      subject: "Weekly digest",
      urgency: 0.05,
      age_hours: 48.0,
      requires_reply: false,
      sentiment: 0.0,
    },
    {
      email_id: "em_10",
      sender_id: "c_report",
      subject: "Blocked on API access — can you help?",
      urgency: 0.75,
      age_hours: 3.0,
      requires_reply: true,
      sentiment: -0.1,
    },
  ],
  relationships: [
    {
      contact_id: "c_partner",
      name: "Alex Chen",
      relationship_kind: "partner",
      closeness: 0.92,
      trust: 0.95,
      last_contact_hours: 3.0,
      tone_preference: "warm",
    },
    {
      contact_id: "c_boss",
      name: "Rajesh Kumar",
      relationship_kind: "boss",
      closeness: 0.55,
      trust: 0.7,
      last_contact_hours: 18.0,
      tone_preference: "formal",
    },
    {
      contact_id: "c_priya",
      name: "Priya Sharma",
      relationship_kind: "colleague",
      closeness: 0.65,
      trust: 0.8,
      last_contact_hours: 6.0,
      tone_preference: "casual",
    },
    {
      contact_id: "c_marco",
      name: "Marco Ruiz",
      relationship_kind: "friend",
      closeness: 0.78,
      trust: 0.85,
      last_contact_hours: 72.0,
      tone_preference: "casual",
    },
    {
      contact_id: "c_mom",
      name: "Mom",
      relationship_kind: "family",
      closeness: 0.88,
      trust: 0.95,
      last_contact_hours: 36.0,
      tone_preference: "warm",
    },
    {
      contact_id: "c_report",
      name: "Devon Lee",
      relationship_kind: "report",
      closeness: 0.4,
      trust: 0.75,
      last_contact_hours: 9.0,
      tone_preference: "direct",
    },
  ],
  pending_tasks: [
    {
      task_id: "t_01",
      title: "Draft Q3 planning doc",
      priority: 0.9,
      deadline_hours: 8.0,
      estimated_minutes: 90,
      delegatable: false,
      assignee_id: null,
      status: "open",
    },
    {
      task_id: "t_02",
      title: "Pay invoice #4412",
      priority: 0.7,
      deadline_hours: -24.0,
      estimated_minutes: 5,
      delegatable: true,
      assignee_id: null,
      status: "open",
    },
    {
      task_id: "t_03",
      title: "Book anniversary flowers",
      priority: 0.85,
      deadline_hours: 30.0,
      estimated_minutes: 10,
      delegatable: false,
      assignee_id: null,
      status: "open",
    },
    {
      task_id: "t_04",
      title: "Review design mock v2",
      priority: 0.55,
      deadline_hours: 20.0,
      estimated_minutes: 25,
      delegatable: false,
      assignee_id: null,
      status: "open",
    },
    {
      task_id: "t_05",
      title: "Unblock Devon on API access",
      priority: 0.75,
      deadline_hours: 4.0,
      estimated_minutes: 15,
      delegatable: false,
      assignee_id: null,
      status: "open",
    },
  ],
  reward_breakdown: mockRewardBreakdown,
};

const BASE_TS = 1_745_500_000_000;

export const mockEvents: GwAgentEvent[] = [
  {
    session_id: MOCK_SESSION_ID,
    kind: "session_start",
    payload: { mode: "simulated" },
    ts_ms: BASE_TS,
  },
  {
    session_id: MOCK_SESSION_ID,
    kind: "partial_transcript",
    payload: { text: "Reschedule the dentist", is_final: false },
    ts_ms: BASE_TS + 420,
  },
  {
    session_id: MOCK_SESSION_ID,
    kind: "partial_transcript",
    payload: {
      text: "Reschedule the dentist to tomorrow",
      is_final: false,
    },
    ts_ms: BASE_TS + 780,
  },
  {
    session_id: MOCK_SESSION_ID,
    kind: "final_transcript",
    payload: {
      text: "Reschedule the dentist to tomorrow afternoon.",
      is_final: true,
      confidence: 0.94,
    },
    ts_ms: BASE_TS + 1100,
  },
  {
    session_id: MOCK_SESSION_ID,
    kind: "tool_call",
    payload: {
      tool_name: "calendar.reschedule",
      arguments: { event_id: "ev_0002", new_day_offset: 1, new_hour: 14.0 },
    },
    ts_ms: BASE_TS + 1480,
  },
  {
    session_id: MOCK_SESSION_ID,
    kind: "reply_text",
    payload: {
      text: "Done — dentist moved to tomorrow at 2pm. You still have the design review at 10.",
    },
    ts_ms: BASE_TS + 1860,
  },
  {
    session_id: MOCK_SESSION_ID,
    kind: "env_step",
    payload: {
      action_id: 2,
      target_id: "ev_0002",
      step_count: 7,
    },
    ts_ms: BASE_TS + 1920,
  },
  {
    session_id: MOCK_SESSION_ID,
    kind: "reward",
    payload: {
      breakdown: mockRewardBreakdown,
      running_total: mockRunningTotal,
    },
    ts_ms: BASE_TS + 1960,
  },
];
